[manager]
keymap = [
  { on = "<F5>", run = "shell --block 'wl-paste -t image/png > /tmp/pasted.png'", desc = "Paste clipboard" },
  { on = "k",          run = "arrow -1" },
  { on = "j",          run = "arrow 1" },
  { on = "<Up>",       run = "arrow -1" },
  { on = "<Down>",     run = "arrow 1" },
  { on = "<C-u>",      run = "arrow -50%" },
  { on = "<C-d>",      run = "arrow 50%" },
  { on = "<C-b>",      run = "arrow -100%" },
  { on = "<C-f>",      run = "arrow 100%" },
  { on = "<PageUp>",   run = "arrow -100%" },
  { on = "<PageDown>", run = "arrow 100%" },

  { on = "h",          run = "leave" },
  { on = "l",          run = "enter" },
  { on = "<Left>",     run = "leave" },
  { on = "<Right>",    run = "enter" },
  { on = "<Enter>",    run = "open" },
  { on = "o",          run = "open" },
  { on = "O",          run = "open --interactive" },

  { on = ["g", "g"],   run = "arrow -99999999" },
  { on = "G",          run = "arrow 99999999" },

  { on = "t",          run = "tab_create --current" },
  { on = "[",          run = "tab_switch -1 --relative" },
  { on = "]",          run = "tab_switch 1 --relative" },
  { on = "1",          run = "tab_switch 0" },
  { on = "2",          run = "tab_switch 1" },
  { on = "3",          run = "tab_switch 2" },
  { on = "4",          run = "tab_switch 3" },
  { on = "5",          run = "tab_switch 4" },
  { on = "<C-w>",      run = "tab_close" },

  { on = "<Space>",    run = ["select --state=none", "arrow 1"] },
  { on = "v",          run = "visual_mode" },
  { on = "V",          run = "select_all --state=none" },
  { on = "<Esc>",      run = "escape" },

  { on = "y",          run = "yank" },
  { on = "d",          run = "yank --cut" },
  { on = "p",          run = "paste" },
  { on = "P",          run = "paste --force" },
  { on = "Y",          run = "unyank" },

  { on = "r",          run = "rename --cursor=before_ext" },
  { on = "a",          run = "create" },
  { on = "D",          run = "remove" },
  { on = "<Delete>",   run = "remove --permanently" },

  { on = "/",          run = "find --smart" },
  { on = "?",          run = "find --previous --smart" },
  { on = "n",          run = "find_arrow" },
  { on = "N",          run = "find_arrow --previous" },
  { on = "f",          run = "filter --smart" },

  { on = ["s", "n"],   run = "sort natural --dir-first" },
  { on = ["s", "m"],   run = "sort modified --dir-first --reverse" },
  { on = ["s", "s"],   run = "sort size --dir-first --reverse" },
  { on = ["s", "e"],   run = "sort extension --dir-first" },

  { on = "zh",         run = "hidden toggle" },

  { on = "!",          run = "shell --interactive --block" },
  { on = "$",          run = "shell --interactive" },

  { on = ["c", "p"],   run = "copy path" },
  { on = ["c", "d"],   run = "copy dirname" },
  { on = ["c", "f"],   run = "copy filename" },

  { on = ["g", "h"],   run = "cd ~" },
  { on = ["g", "c"],   run = "cd ~/.config" },
  { on = ["g", "D"],   run = "cd ~/Downloads" },
  { on = ["g", "r"],   run = "cd /" },
  { on = ["g", "t"],   run = "cd /tmp" },

  #plugins 
  { on = "F",          run = "plugin jump-to-char" },

  { on = "l",          run = "plugin smart-enter" },
  { on = "<Right>",    run = "plugin smart-enter" },
  { on = "<Enter>",    run = "plugin smart-enter" },

  { on = "f",          run = "plugin smart-filter" },

  { on = "<C-p>",      run = "plugin toggle-pane --args=parent" },
  { on = "<C-]>",      run = "plugin toggle-pane --args=preview" },

  { on = "<C-s>",      run = "plugin what-size" },

  { on = ["g", "l"],   run = "plugin lazygit" },

  { on = ["u", "a"],   run = "plugin yamb -- save" },
  { on = ["u", "g"],   run = "plugin yamb -- jump_by_key" },
  { on = ["u", "G"],   run = "plugin yamb -- jump_by_fzf" },
  { on = ["u", "d"],   run = "plugin yamb -- delete_by_key" },
  { on = ["u", "D"],   run = "plugin yamb -- delete_by_fzf" },

  { on = ["c", "s"],   run = "plugin sudo" },

  { on = "~",          run = "help" },
  { on = "<F1>",       run = "help" },
  { on = "q",          run = "quit" },
  { on = "Q",          run = "quit --no-cwd-file" },
  { on = "<C-c>",      run = "quit --no-cwd-file" },
  { on = "<C-r>",      run = "refresh" },
  { on = "T",          run = "tasks_show" },
]

[tasks]
keymap = [
  { on = "<Esc>",   run = "close" },
  { on = "q",       run = "close" },
  { on = "k",       run = "arrow -1" },
  { on = "j",       run = "arrow 1" },
  { on = "<Up>",    run = "arrow -1" },
  { on = "<Down>",  run = "arrow 1" },
  { on = "<Enter>", run = "inspect" },
  { on = "x",       run = "cancel" },
  { on = "~",       run = "help" },
]

[select]
keymap = [
  { on = "<Esc>",   run = "close" },
  { on = "<C-c>",   run = "close" },
  { on = "k",       run = "arrow -1" },
  { on = "j",       run = "arrow 1" },
  { on = "<Up>",    run = "arrow -1" },
  { on = "<Down>",  run = "arrow 1" },
  { on = "<Enter>", run = "close --submit" },
  { on = "~",       run = "help" },
]

[input]
keymap = [
  { on = "<Esc>",       run = "close" },
  { on = "<Enter>",     run = "close --submit" },
  { on = "<C-c>",       run = "close" },

  { on = "<Left>",      run = "move -1" },
  { on = "<Right>",     run = "move 1" },
  { on = "<C-Left>",    run = "backward-word" },
  { on = "<C-Right>",   run = "forward-word" },
  { on = "<Home>",      run = "move -999" },
  { on = "<End>",       run = "move 999" },
  { on = "<C-a>",       run = "move -999" },
  { on = "<C-e>",       run = "move 999" },

  { on = "<Backspace>", run = "backspace" },
  { on = "<Delete>",    run = "delete" },
  { on = "<C-u>",       run = "kill-line-start" },
  { on = "<C-k>",       run = "kill-line-end" },
  { on = "<C-w>",       run = "backward-kill-word" },

  { on = "<Up>",        run = "history-prev" },
  { on = "<Down>",      run = "history-next" },

  { on = "~",           run = "help" },
]

[confirm]
keymap = [
  { on = "<Esc>",   run = "close" },
  { on = "<C-c>",   run = "close" },
  { on = "n",       run = "close" },
  { on = "<Enter>", run = "close --submit" },
  { on = "y",       run = "close --submit" },
  { on = "k",       run = "arrow -1" },
  { on = "j",       run = "arrow 1" },
  { on = "~",       run = "help" },
]

[help]
keymap = [
  { on = "<Esc>", run = "escape" },
  { on = "q",     run = "close" },
  { on = "k",     run = "arrow -1" },
  { on = "j",     run = "arrow 1" },
  { on = "<Up>",  run = "arrow -1" },
  { on = "<Down>",run = "arrow 1" },
  { on = "/",     run = "filter" },
]
[mgr]
prepend_keymap = [
  { on = "<F5>", run = ["shell --block -- sh -c 'wl-paste -t image/png > /tmp/clip.png'", "reveal /tmp/clip.png", "open"], desc = "Paste clipboard" },
]
