{ pkgs, inputs, ... }:
{
    home.packages = with pkgs; [
      libnotify
      ada
      flake-edit
      tokei
      awww
      sshfs
      ffmpeg
      mpvpaper
      imagemagick
      wtype
      pipx
      python312
      fd
      proton-vpn-cli
      nautilus
      portablemc
      wayvnc
      wl-clipboard
      gallery-dl
      gamescope
      gamemode
      clang
      mold
      cargo-generate
      radeontop
      flatpak
      jdk17
      apktool
      parted
      gparted
      dust
      duf
      nvd
      veracrypt
      ffmpeg
      file
      yazi
      tree
      tmux
      chameleos
      mpv
      btop
      fastfetch
      materialgram
      librewolf
      zoxide
      eza
      aria2
      foot
      bibata-cursors
      nwg-look
      papirus-icon-theme
      rustup 
      lutris
      p7zip
      alsa-lib
      inputs.niux.packages.${pkgs.system}.default 
      home-manager
      (inputs.quickshell.packages.${pkgs.system}.default.withModules [
      pkgs.kdePackages.qtmultimedia
      pkgs.ffmpeg
      pkgs.gst_all_1.gst-plugins-good
      pkgs.gst_all_1.gst-libav
      ])
      #end
    ];
}
