{ pkgs, inputs, ... }:
{
    home.packages = with pkgs; [
      android-tools
      rustup
      cargo-clone
      ffmpeg
      fluffychat
      ouch
      amdgpu_top
      dust
      bubblewrap
      jq
      wineWow64Packages.full
      usbutils
      cyme
      wl-clipboard
      catppuccin-qt5ct
      mpvpaper
      yt-dlp
      librewolf
      _7zz-rar
      scrcpy
      qpwgraph
      wakatime-cli
      awatcher
      obsidian
      innoextract
      imv
      sd
      ripgrep
      bat
      procs
      vulkan-tools
      winetricks
      libnotify
      flake-edit
      tokei
      awww
      mpvpaper
      imagemagick
      wtype
      python312
      fd
      proton-vpn-cli
      nautilus
      portablemc
      wayvnc
      wl-clipboard
      gallery-dl
      gamescope
      gamemode
      clang
      mold
      cargo-generate
      flatpak
      jdk17
      parted
      gparted
      duf
      nvd
      veracrypt
      file
      yazi
      tree
      tmux
      chameleos
      mpv
      btop
      fastfetch
      materialgram
      zoxide
      eza
      aria2
      foot
      bibata-cursors
      nwg-look
      papirus-icon-theme
      lutris
      alsa-lib
      inputs.rip2.packages.${pkgs.system}.default
      inputs.niux.packages.${pkgs.system}.default 
      inputs.concord.packages.${pkgs.system}.default
      home-manager
      (inputs.quickshell.packages.${pkgs.system}.default.withModules [
      pkgs.kdePackages.qtmultimedia
      pkgs.ffmpeg
      pkgs.gst_all_1.gst-plugins-good
      pkgs.gst_all_1.gst-libav
      ])
      pavucontrol
#end
    ];
    nixpkgs.config.permittedInsecurePackages = [
        "librewolf-151.0.2-1"
        "librewolf-unwrapped-151.0.2-1"
    ];
}